logging_params:
  log_dir: "logs"
  name: "joint_model"

schedules_path: "./tmp/nts_home_schedules.csv"
attributes_path: "./tmp/nts_home_attributes.csv"

conditionals:
  work_status: nominal

attribute_encoder: "tokens"

encoder_params:
  name: "sequence"
  max_length: 12
  norm_duration: 1440
  jitter: 0.2

model_params:
  name: "JVAESeqLSTM"
  hidden_layers: 3
  hidden_size: 128
  latent_dim: 6
  dropout: 0.1
  teacher_forcing_ratio: 0.5

loader_params:
  train_batch_size: 1024
  val_batch_size:  1024
  num_workers: 8

experiment_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.0001

trainer_params:
  min_epochs: 40
  patience: 30
  max_epochs: 100

seed: 1234
