logging_params:
  log_dir: "logs"
  name: "label_model"

schedules_path: "./tmp/nts_home_schedules.csv"
attributes_path: "./tmp/nts_home_attributes_groups.csv"

conditionals:
  gender: nominal
  work_status: nominal

attribute_encoder: "tokens"

encoder_params:
  name: "sequence"
  max_length: 12
  norm_duration: 1440
  jitter: 0.2

model_params:
  name: "LabelFeedForward"
  hidden_layers: 3
  hidden_size: 128
  latent_dim: 0
  dropout: 0.3

loader_params:
  train_batch_size: 1024
  val_batch_size:  1024
  num_workers: 8

experiment_params:
  LR: 0.00001
  weight_decay: 0.0
  scheduler_gamma: 0.95
  label_loss_weight: 1.0

trainer_params:
  min_epochs: 10
  patience: 10
  max_epochs: 100

seed: 1234
