name: Development docs CI

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - tests/**

jobs:
  docs-test:
    if: github.ref != 'refs/heads/main'
    uses: fredshone/actions/.github/workflows/docs-deploy.yml@main
    with:
      deploy_type: test
      notebook_kernel: caveat

  docs-update-latest:
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main'
    uses: fredshone/actions/.github/workflows/docs-deploy.yml@main
    with:
      deploy_type: update_latest
      notebook_kernel: caveat